version: '3.9'

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
        networks:
            - proxy_network
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${RSOCKET_PORT}:${RSOCKET_PORT}

        environment:
            SERVER_ADDR: ${SERVER_ADDR}
            SERVER_PORT: ${SERVER_PORT}
            RSOCKET_PORT: ${RSOCKET_PORT}

            PRODUCER_PORT: ${PRODUCER_PORT}
            LOAD_BALANCER: ${LOAD_BALANCER}

        deploy:
            replicas: 1
            placement:
                constraints: [node.labels.mgmt != true ]

networks:
    proxy_network:
        external: true