version: '3.9'

services:
    app:
        image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}
        networks:
            - proxy_network
        ports:
            - ${RSOCKET_PORT}:${RSOCKET_PORT}

        environment:
            SERVER_ADDR: ${SERVER_ADDR}
            SERVER_PORT: ${SERVER_PORT}
            RSOCKET_PORT: ${RSOCKET_PORT}

            PRODUCER_PORT: ${PRODUCER_PORT}
            LOAD_BALANCER: ${LOAD_BALANCER}

            ERROR_LOGS: ${ERROR_LOGS}
            KAFKA_BROKER: ${KAFKA_BROKER}
            GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

            API_PARAMS: ${API_PARAMS}

        deploy:
            replicas: ${REPLICAS}

networks:
    proxy_network:
        external: true