version: '3.9'

services:
    app:
        image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}
        networks:
            - proxy_network
        ports:
            - ${RSOCKET_PORT}:${RSOCKET_PORT}

        environment:
            SERVER_ADDR: ${SERVER_ADDR}
            SERVER_PORT: ${SERVER_PORT}
            RSOCKET_PORT: ${RSOCKET_PORT}

            PRODUCER_PORT: ${PRODUCER_PORT}
            LOAD_BALANCER: ${LOAD_BALANCER}

            ADMIN_PANEL: ${ADMIN_PANEL}
            BASE64_IMAGE_TO_LINK_CONVERTER_API: ${BASE64_IMAGE_TO_LINK_CONVERTER_API}

            ERROR_LOGS: ${ERROR_LOGS}
            KAFKA_BROKER: ${KAFKA_BROKER}
            GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

            LOGIN_FOR_GAI_TOKEN: ${LOGIN_FOR_GAI_TOKEN}
            CURRENT_SYSTEM_FOR_GAI: ${CURRENT_SYSTEM_FOR_GAI}
            PASSWORD_FOR_GAI_TOKEN: ${PASSWORD_FOR_GAI_TOKEN}

            LOGIN_FOR_FIO_TOKEN: ${LOGIN_FOR_FIO_TOKEN}
            CURRENT_SYSTEM_FOR_FIO: ${CURRENT_SYSTEM_FOR_FIO}
            PASSWORD_FOR_FIO_TOKEN: ${PASSWORD_FOR_FIO_TOKEN}

            API_FOR_GAI_TOKEN: ${API_FOR_GAI_TOKEN}
            API_FOR_TONIROVKA: ${API_FOR_TONIROVKA}
            API_FOR_VEHICLE_DATA: ${API_FOR_VEHICLE_DATA}
            API_FOR_FOR_INSURANCE: ${API_FOR_FOR_INSURANCE}
            API_FOR_VIOLATION_LIST: ${API_FOR_VIOLATION_LIST}
            API_FOR_DOVERENNOST_LIST: ${API_FOR_DOVERENNOST_LIST}
            API_FOR_MODEL_FOR_CAR_LIST: ${API_FOR_MODEL_FOR_CAR_LIST}

            API_FOR_PINPP: ${API_FOR_PINPP}
            API_FOR_CADASTR: ${API_FOR_CADASTR}
            API_FOR_FIO_TOKEN: ${API_FOR_FIO_TOKEN}
            API_FOR_PERSON_IMAGE: ${API_FOR_PERSON_IMAGE}
            API_FOR_PASSPORT_MODEL: ${API_FOR_PASSPORT_MODEL}
            API_FOR_MODEL_FOR_ADDRESS: ${API_FOR_MODEL_FOR_ADDRESS}
            API_FOR_PERSON_DATA_FROM_ZAKS: ${API_FOR_PERSON_DATA_FROM_ZAKS}
            API_FOR_TRAIN_TICKET_CONSUMER_SERVICE: ${API_FOR_TRAIN_TICKET_CONSUMER_SERVICE}

        deploy:
            replicas: ${REPLICAS}

networks:
    proxy_network:
        external: true