server:
    port: 6006
    address: 0.0.0.0

spring:
    data:
        cassandra:
            port: 9942
            keyspace-name: TRACKERS
            contact-points: 10.254.1.227
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: 10s

            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

    kafka:
        bootstrap-servers: 10.254.1.209:9092, 10.254.1.211:9092, 10.254.1.212:9092

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

        consumer:
            group-id: SSD.TRACKERS
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringSerializer
            value-deserializer: org.apache.kafka.common.serialization.StringSerializer

        admin:
            client-id: SSD.TRACKERS

    rsocket:
        server:
            port: 6066
            address: 10.254.1.229