server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    RSOCKET_VARIABLES:
        PRODUCER_PORT : ${PRODUCER_PORT:5056}
        LOAD_BALANCER : ${LOAD_BALANCER:ms-backend.ssd.uz}

    KAFKA_VARIABLES:
        ERROR_LOGS: ${ERROR_LOGS:ERROR_LOGS}
        ADMIN_PANEL: adminpanel_integratedServicesUserLog_0.0.1
        ADMIN_PANEL_ERROR_LOG: ${ADMIN_PANEL_ERROR_LOG:adminpanel_integratedServicesLog_0.0.1}

        KAFKA_BROKER: ${KAFKA_BROKER:10.254.6.1, 10.254.6.2, 10.254.6.3}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:PSYCHOLOGY-CARD-SERVICE}

    GAI_VARIABLES:
        API_FOR_GAI_TOKEN: ${API_FOR_GAI_TOKEN:http://172.250.1.65:7101/Agency/token}
        LOGIN_FOR_GAI_TOKEN: SharafIT_PSP
        CURRENT_SYSTEM_FOR_GAI: 40
        PASSWORD_FOR_GAI_TOKEN: Sh@r@fITP@$P

        API_FOR_TONIROVKA: ${API_FOR_TONIROVKA:http://172.250.1.67:7145/api/Vehicle/TintingInformation?platenumber=}
        API_FOR_VEHICLE_DATA: ${API_FOR_VEHICLE_DATA:http://172.250.1.67:7145/api/Vehicle/VehicleInformation?platenumber=}
        API_FOR_FOR_INSURANCE: ${API_FOR_FOR_INSURANCE:http://172.250.1.67:7145/api/Vehicle/InsuranceInformation?platenumber=}
        API_FOR_VIOLATION_LIST: ${API_FOR_VIOLATION_LIST:http://172.250.1.67:7145/api/Vehicle/ViolationsInformation?PlateNumber=}
        API_FOR_DOVERENNOST_LIST: ${API_FOR_DOVERENNOST_LIST:http://172.250.1.67:7145/api/Vehicle/AttorneyInformation?platenumber=}
        API_FOR_MODEL_FOR_CAR_LIST: ${API_FOR_MODEL_FOR_CAR_LIST:http://172.250.1.67:7145/api/Vehicle/PersonVehiclesInformation?pinpp=}

    OVIR_VARIABLES:
        API_FOR_PINPP: ${API_FOR_PINPP:http://172.250.1.67:7145/PersonInformation?pinpp=}
        API_FOR_CADASTR: ${API_FOR_CADASTR:http://172.250.1.67:7121/api/CensusOut/PersonsInCadastre}
        API_FOR_PERSON_IMAGE: ${API_FOR_PERSON_IMAGE:http://172.250.1.67:7145/GetPhotoByPinpp?pinpp=}
        API_FOR_PASSPORT_MODEL: ${API_FOR_PASSPORT_MODEL:http://172.250.1.67:7121/api/CensusOut/GetPerson}
        API_FOR_BOARD_CROSSING: ${API_FOR_BOARD_CROSSING:http://10.130.12.9:7006/DWebServices/json/mvd/getPersonBC}
        API_FOR_MODEL_FOR_ADDRESS: ${API_FOR_MODEL_FOR_ADDRESS:http://172.250.1.67:7121/api/CensusOut/GetAddress}
        BASE64_IMAGE_TO_LINK_CONVERTER_API: https://ms.ssd.uz/files/api/v1/image/base64