server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    PRODUCER_PORT: ${PRODUCER_PORT}
    LOAD_BALANCER: ${LOAD_BALANCER}

    ERROR_LOGS: ${ERROR_LOGS}
    KAFKA_BROKER: ${KAFKA_BROKER}
    GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

    API_PARAMS: ${API_PARAMS}
