server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    PRODUCER_PORT: ${PRODUCER_PORT}
    LOAD_BALANCER: ${LOAD_BALANCER}

    ERROR_LOGS: ${ERROR_LOGS}
    KAFKA_BROKER: ${KAFKA_BROKER}
    GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

    API_FOR_GAI_TOKEN: http://172.250.1.65:7101/Agency/token
    API_FOR_TONIROVKA: http://172.250.1.67:7145/api/Vehicle/TintingInformation?platenumber=
    API_FOR_VEHICLE_DATA: http://172.250.1.67:7145/api/Vehicle/VehicleInformation?platenumber=
    API_FOR_FOR_INSURANCE: http://172.250.1.67:7145/api/Vehicle/InsuranceInformation?platenumber=
    API_FOR_VIOLATION_LIST: http://172.250.1.67:7145/api/Vehicle/ViolationsInformation?PlateNumber=
    API_FOR_DOVERENNOST_LIST: http://172.250.1.67:7145/api/Vehicle/AttorneyInformation?platenumber=
    API_FOR_MODEL_FOR_CAR_LIST: http://172.250.1.67:7145/api/Vehicle/PersonVehiclesInformation?pinpp=

    API_FOR_PINPP : http://172.250.1.67:7145/PersonInformation?pinpp=
    API_FOR_CADASTR : http://172.250.1.67:7121/api/CensusOut/PersonsInCadastre
    API_FOR_FIO_TOKEN : http://172.250.1.203:9292/Auth/Agency/token
    API_FOR_PERSON_IMAGE: http://172.250.1.67:7145/GetPhotoByPinpp?pinpp=
    API_FOR_PASSPORT_MODEL : http://172.250.1.67:7121/api/CensusOut/GetPerson
    API_FOR_MODEL_FOR_ADDRESS : http://172.250.1.67:7121/api/CensusOut/GetAddress
    API_FOR_PERSON_DATA_FROM_ZAKS : http://172.250.1.203:9292/Zags/api/v1/ZagsReference/GetPersonInfo
    API_FOR_TRAIN_TICKET_CONSUMER_SERVICE : http://ms.ssd.uz/train-ticket-consumer/api/v1/photo?passportNumber=
