server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    PRODUCER_PORT: ${PRODUCER_PORT}
    LOAD_BALANCER: ${LOAD_BALANCER}
