server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    PRODUCER_PORT : ${PRODUCER_PORT}
    LOAD_BALANCER : ${LOAD_BALANCER}

    ERROR_LOGS : ${ERROR_LOGS}
    ADMIN_PANEL : adminpanel_integratedServicesUserLog_0.0.1

    KAFKA_BROKER : ${KAFKA_BROKER}
    GROUP_ID_FOR_KAFKA : ${GROUP_ID_FOR_KAFKA}

    LOGIN_FOR_GAI_TOKEN : ${LOGIN_FOR_GAI_TOKEN}
    CURRENT_SYSTEM_FOR_GAI : ${CURRENT_SYSTEM_FOR_GA}
    PASSWORD_FOR_GAI_TOKEN : ${PASSWORD_FOR_GAI_TOKEN}

    LOGIN_FOR_FIO_TOKEN : ${LOGIN_FOR_FIO_TOKEN}
    CURRENT_SYSTEM_FOR_FIO : ${CURRENT_SYSTEM_FOR_FIO}
    PASSWORD_FOR_FIO_TOKEN : ${PASSWORD_FOR_FIO_TOKEN}

    API_FOR_GAI_TOKEN : ${API_FOR_GAI_TOKEN}
    API_FOR_TONIROVKA : ${API_FOR_TONIROVKA}
    API_FOR_FOR_INSURANCE : ${API_FOR_INSURANCE}
    API_FOR_VEHICLE_DATA : ${API_FOR_VEHICLE_DATA}
    API_FOR_VIOLATION_LIST : ${API_FOR_VIOLATION_LIST}
    API_FOR_DOVERENNOST_LIST : ${API_FOR_DOVERENNOST_LIST}
    API_FOR_MODEL_FOR_CAR_LIST : ${API_FOR_MODEL_FOR_CAR_LIST}

    API_FOR_PINPP : ${API_FOR_PINPP}
    API_FOR_CADASTR : ${API_FOR_CADASTR}
    API_FOR_FIO_TOKEN : ${API_FOR_FIO_TOKEN}
    API_FOR_PERSON_IMAGE : ${API_FOR_PERSON_IMAGE}
    API_FOR_PASSPORT_MODEL : ${API_FOR_PASSPORT_MODEL}
    API_FOR_MODEL_FOR_ADDRESS : ${API_FOR_MODEL_FOR_ADDRESS}
    API_FOR_PERSON_DATA_FROM_ZAKS : ${API_FOR_PERSON_DATA_FROM_ZAKS}
    API_FOR_TRAIN_TICKET_CONSUMER_SERVICE : ${API_FOR_TRAIN_TICKET_CONSUMER_SERVICE}