server:
    port: ${SERVER_PORT} # 6006
    address: ${SERVER_ADDR} # 0.0.0.0

spring:
    data:
        cassandra:
            port: ${CASSANDRA_PORT}
            keyspace-name: ${KEYSPACE_NAME}
            contact-points: ${CASSANDRA_HOST}
            local-datacenter: ${CASSANDRA_DC}
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: ${REQUEST_TIMEOUT_FOR_CASSANDRA}

            connection:
                connect-timeout: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
                init-query-timeout: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    PRODUCER_PORT: ${PRODUCER_PORT} # 5055
    LOAD_BALANCER: ${LOAD_BALANCER} # ms-backend.ssd.uz
