server:
    port: ${SERVER_PORT:6067}
    address: ${SERVER_ADDR:localhost}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT:6060}
            address: ${SERVER_ADDR:localhost}

variables:
    RSOCKET_VARIABLES:
        PRODUCER_PORT : ${PRODUCER_PORT:5056}
        LOAD_BALANCER : ${LOAD_BALANCER:localhost}

    KAFKA_VARIABLES:
        ERROR_LOGS: ${ERROR_LOGS:ERROR_LOGS}
        ADMIN_PANEL: adminpanel_integratedServicesUserLog_0.0.1
        ADMIN_PANEL_ERROR_LOG: ${ADMIN_PANEL_ERROR_LOG}

        KAFKA_BROKER: ${KAFKA_BROKER:localhost:9092}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:PSYCHOLOGY-CARD-SERVICE}

    GAI_VARIABLES:
        API_FOR_GAI_TOKEN: ${API_FOR_GAI_TOKEN}
        LOGIN_FOR_GAI_TOKEN: SharafIT_PSP
        CURRENT_SYSTEM_FOR_GAI: 40
        PASSWORD_FOR_GAI_TOKEN: Sh@r@fITP@$P

        API_FOR_TONIROVKA: ${API_FOR_TONIROVKA}
        API_FOR_VEHICLE_DATA: ${API_FOR_VEHICLE_DATA}
        API_FOR_FOR_INSURANCE: ${API_FOR_FOR_INSURANCE}
        API_FOR_VIOLATION_LIST: ${API_FOR_VIOLATION_LIST}
        API_FOR_DOVERENNOST_LIST: ${API_FOR_DOVERENNOST_LIST}
        API_FOR_MODEL_FOR_CAR_LIST: ${API_FOR_MODEL_FOR_CAR_LIST}

    OVIR_VARIABLES:
        API_FOR_PINPP: ${API_FOR_PINPP}
        API_FOR_CADASTR: ${API_FOR_CADASTR}
        API_FOR_PERSON_IMAGE: ${API_FOR_PERSON_IMAGE}
        API_FOR_PASSPORT_MODEL: ${API_FOR_PASSPORT_MODEL}
        API_FOR_BOARD_CROSSING: ${API_FOR_BOARD_CROSSING}
        API_FOR_MODEL_FOR_ADDRESS: ${API_FOR_MODEL_FOR_ADDRESS}
        BASE64_IMAGE_TO_LINK_CONVERTER_API: ${BASE64_IMAGE_TO_LINK_CONVERTER_API}