spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT} # 6066
            address: ${SERVER_ADDR} # 0.0.0.0

server:
    port: ${SERVER_PORT} # 6006
    address: ${SERVER_ADDR} # 0.0.0.0

variables:
    PRODUCER_PORT: ${PRODUCER_PORT} # 5055
    LOAD_BALANCER: ${LOAD_BALANCER} # ms-backend.ssd.uz
