#server:
#    port: 6006
#    address: 10.254.1.229
#
#spring:
#    rsocket:
#        server:
#            port: 6066
#            address: 10.254.1.229

server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDRESS}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDRESS}