package com.ssd.mvd.constants;

public enum Details {
    // for Card
    DETAILS, ADDRESS_OF_APPLICANT, APPLICANT_DATA, ADDRESS_OF_INCIDENT, DATA_OF_VICTIM, ADDRESS_OF_VICTIM, ADDITIONAL_ADDRESS, ADDITIONAL_ADDRESS_OF_APPLICANT, ADDITIONAL_ADDRESS_OF_Victim,

    // for SElfEmployment
    NUMBER, ACCEPTED_TIME, ACCEPTED_POINT_LATITUDE, ACCEPTED_POINT_LONGITUDE, ARRIVED_TIME, ARRIVED_POINT_LATITUDE, ARRIVED_POINT_LONGITUDE, REPORT, REPORT_TIME, DESCRIPTION, ADDRESS, SELF_EMPLOYMENT
}
