package com.ssd.mvd.constants;

public enum Details {
    DETAILS, ADDRESS_OF_APPLICANT, APPLICANT_DATA, ADDRESS_OF_INCIDENT, DATA_OF_VICTIM, ADDRESS_OF_VICTIM, ADDITIONAL_ADDRESS, ADDITIONAL_ADDRESS_OF_APPLICANT, ADDITIONAL_ADDRESS_OF_Victim
}
