package com.ssd.mvd.constants;

public enum Methods {
    CADASTER,
    GET_PINPP,
    UPDATE_TOKENS,
    GET_INSURANCE,
    GET_TONIROVKA,
    BASE64_TO_LINK,
    GET_VEHILE_DATA,
    GET_DATA_BY_FIO,
    GET_VIOLATION_LIST,
    GET_IMAGE_BY_PINFL,
    GET_DOVERENNOST_LIST,
    GET_MODEL_FOR_ADDRESS,
    GET_MODEL_FOR_PASSPORT,
    GET_MODEL_FOR_CAR_LIST,
    CONVERT_BASE64_TO_LINK,
    GET_PSYCHOLOGY_CARD_FOR_FOREIGNERS,

    // for RequestController
    GET_CAR_TOTAL_DATA,
    GET_PERSONAL_CADASTOR,
    GET_PERSON_TOTAL_DATA,
    GET_CAR_TOTAL_DATA_BY_PINFL,
    GET_PERSON_TOTAL_DATA_BY_FIO,
    GET_PERSON_TOTAL_DATA_BY_PINFL,
    GET_PERSON_TOTAL_DATA_BY_PASSPORT_AND_BIRTHDATE,

    // for Popilon service
    GET_FACE_CARD,
    GET_VIOLATION_LIST_BY_PINFL,
}
