package com.ssd.mvd.constants;

public enum Methods {
    CADASTER,
    GET_PINPP,
    GET_INSURANCE,
    GET_TONIROVKA,
    BASE64_TO_LINK,
    GET_VEHILE_DATA,
    GET_VIOLATION_LIST,
    GET_IMAGE_BY_PINFL,
    GET_DOVERENNOST_LIST,
    GET_MODEL_FOR_ADDRESS,
    GET_MODEL_FOR_PASSPORT,
    GET_MODEL_FOR_CAR_LIST,
    CONVERT_BASE64_TO_LINK,
}
