package com.ssd.mvd.constants;

public enum Methods {
    CADASTER,
    GET_PINPP,
    GET_IMAGE_BY_PINFL,
    GET_CROSS_BOARDING,
    GET_MODEL_FOR_ADDRESS,
    GET_MODEL_FOR_PASSPORT,

    UPDATE_TOKENS,
    BASE64_TO_LINK,
    GET_DATA_BY_FIO,
    GET_VIOLATION_LIST,
    CONVERT_BASE64_TO_LINK,

    GET_INSURANCE,
    GET_TONIROVKA,
    GET_VEHILE_DATA,
    GET_DOVERENNOST_LIST,
    GET_MODEL_FOR_CAR_LIST,

    // for RequestController
    GET_CAR_TOTAL_DATA,
    GET_PERSONAL_CADASTOR,
    GET_PERSON_TOTAL_DATA,
    GET_CAR_TOTAL_DATA_BY_PINFL,
    GET_PERSON_TOTAL_DATA_BY_FIO,
    GET_PERSON_TOTAL_DATA_BY_PINFL,
    GET_PERSON_TOTAL_DATA_BY_PASSPORT_AND_BIRTHDATE,

    // for Popilon service
    GET_FACE_CARD,
    GET_VIOLATION_LIST_BY_PINFL,
}
